// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFkjX6u0dzoBTV-Znj0MwavNLwyp6cJOM',
    appId: '1:931190725175:web:16ff3e390f404fbfa63db2',
    messagingSenderId: '931190725175',
    projectId: 'financeassistant-72ad0',
    authDomain: 'financeassistant-72ad0.firebaseapp.com',
    databaseURL: 'https://financeassistant-72ad0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'financeassistant-72ad0.firebasestorage.app',
    measurementId: 'G-9R8XRXRL1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8zTFaG0HNckYIUCPQt5ahqKQPmvRz20k',
    appId: '1:931190725175:android:7dc5b7fd3636cbe5a63db2',
    messagingSenderId: '931190725175',
    projectId: 'financeassistant-72ad0',
    databaseURL: 'https://financeassistant-72ad0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'financeassistant-72ad0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZkmyOQFFF4Fbl9H7U4ay3KOrkf5NgOMg',
    appId: '1:931190725175:ios:30bceadf5b55eaaca63db2',
    messagingSenderId: '931190725175',
    projectId: 'financeassistant-72ad0',
    databaseURL: 'https://financeassistant-72ad0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'financeassistant-72ad0.firebasestorage.app',
    iosBundleId: 'com.example.finnanceAssist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZkmyOQFFF4Fbl9H7U4ay3KOrkf5NgOMg',
    appId: '1:931190725175:ios:30bceadf5b55eaaca63db2',
    messagingSenderId: '931190725175',
    projectId: 'financeassistant-72ad0',
    databaseURL: 'https://financeassistant-72ad0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'financeassistant-72ad0.firebasestorage.app',
    iosBundleId: 'com.example.finnanceAssist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFkjX6u0dzoBTV-Znj0MwavNLwyp6cJOM',
    appId: '1:931190725175:web:b2f019b3aa38a3b5a63db2',
    messagingSenderId: '931190725175',
    projectId: 'financeassistant-72ad0',
    authDomain: 'financeassistant-72ad0.firebaseapp.com',
    databaseURL: 'https://financeassistant-72ad0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'financeassistant-72ad0.firebasestorage.app',
    measurementId: 'G-VR23HY1N2V',
  );
}
